### ISSUE TITLE
KaTex subfolder katex needed for ui.js

### ISSUE THREAD

**Issue by DrDanPrice** [varkor/quiver#102]
I installed on a Mac, and after make with no errors had the error that KaTex had failed to load. The references in ui.js at 6788 (src: "KaTex/katex.min.js") and 6807 (href: "KaTex/katex.css") were failing. It worked when I changed to "KaTex/katex/katex.min.js" and "KaTex/katex/katex.css", respectively.
I don't know if that's just an issue with the Mac make (I have gcc make installed) or more generally.
Great work, by the way!

**Comment by varkor** [comment]
Thanks – this could be a holdover when I changed how KaTeX was used. I'll look into it soon.

**Comment by AlexanderZeilmann** [comment]
Changing line 12 in the Makefile https://github.com/varkor/quiver/blob/cfe491824a78382babb015dde86696eaa51b6c60/Makefile#L12 
to 
```
	mv katex/* src/KaTeX/
```
fixes the problem (at least on a Mac).

**Comment by varkor** [comment]
This has been fixed in https://github.com/varkor/quiver/commit/72d85871aaed2dcb3cc351c80ca0ea995aad43e0. The problem was that there was an empty `src/KaTeX` folder after cloning which should not have been there (and `mv` has different behaviour depending on whether the destination folder exists or not).
