### ISSUE TITLE
Local macro file?

### ISSUE THREAD

**Issue by conal** [varkor/quiver#104]
I have **quiver** installed on my computer and would like to place my macro file on my computer as well (rather than on the web). When I use "`file:///...` for the macro location, the macros do not work. Are local macro files supported? If so, is there some trick I'm missing?

**Comment by varkor** [comment]
Unfortunately, using local files is a bit awkward due to [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS): JavaScript can only load URLs from the same origin (though `file://` doesn't count). I think the simplest way to get this to work is to run a basic server on your computer that will serve the local files (and then use **quiver** via `localhost://`). This is a common issue, so there are related questions on StackOverflow: for example, see [the answers here](https://stackoverflow.com/questions/10752055/cross-origin-requests-are-only-supported-for-http-error-when-loading-a-local). It would be nice if I could make this easier to do from **quiver**'s end, but I don't see a good solution at the moment (short of creating an Electron app).

**Comment by conal** [comment]
Thanks very much for the explanation and recommendation! Installing and using a web server on my local machine is a fine solution for my use.

**Comment by user202729** [comment]
I think it should be possible using [html - Reading file contents on the client-side in javascript in various browsers - Stack Overflow](https://stackoverflow.com/questions/750032/reading-file-contents-on-the-client-side-in-javascript-in-various-browsers) . It just require the user to select "upload" on the file --- it doesn't even need a server.

That said, for convenience, it may be a good idea to store the file content into `localStorage`. Needless to say this will fail if the user shares the link though.
