### ISSUE TITLE
Log in to save diagrams

### ISSUE THREAD

**Issue by Daysalos** [varkor/quiver#108]
Any plans on a login function to save diagrams?

**Comment by varkor** [comment]
Most diagrams are for a specific purpose, and it makes more sense to associate them to the particular document they are part of. In what situations do you think it would be useful to be able to save diagrams independently?

**Comment by enjoysmath** [comment]
@Daysalos Abstract Spacecraft (formerly "Quiver Database"), a Django project of mine will support this feature.  You will eventually be able to log in with OAuth2.   You can edit any diagram you own or have permissions to edit.  I'm new to Django, so it will be simple at first.  But eventually you will be able to construct some forms of diagram chases.  The whole chase will be stored in a graph database.  The first diagram and the last diagram together put into a DiagramRule make up what we usually call a Theorem or Lemma.   So imagine making diagram chase decisions by clicking buttons.  It won't replace paper since drawing diagrams by hand is irreplaceable, it will though act as a good proof reference.  Not only will you see one case within the splitting lemma proof, but all cases will be proven and stored.  Editors will get a cut of the site's profit if we do it that way, but we need some kind of money donated in order to afford faster hosting on Digital Ocean or Graphene DB.

**Comment by varkor** [comment]
Closing as I don't see much of a benefit from an account system, which would in any case be a significant increase in complexity.
