### ISSUE TITLE
Can't display certain arrow

### ISSUE THREAD

**Issue by CanaanZhou** [varkor/quiver#141]
It's a very specific bug I found. What I did was:

1. write f^{-1}(V) in a square,
2. write \Lambda(f^* G) on the up-right square of the previous one,
3. draw an arrow from the first square to the second one.

Somehow the arrow doesn't display.

If I change the text a bit, say, write f^{-1}(A) instead f^{-1}(V) in the first square, the arrow now displays correctly. If I change the position of the squares, say, put the second square on the right of the first square, instead of up-right, the arrow also displays. It's kinda strange.
![image](https://user-images.githubusercontent.com/70128860/177699198-aed11344-2ceb-4fd8-9e74-abb50de9092d.png)

**Comment by varkor** [comment]
Thanks for the detailed bug report! This is indeed a strange issue. I'll look into it now.

Edit: a little progress. The reason this is happening is because this error is being triggered, though it should never be: https://github.com/varkor/quiver/blob/cd18afac251e0fd5bb65d828386bbff1c03bef18/src/bezier.js#L258

**Comment by varkor** [comment]
This has been fixed in https://github.com/varkor/quiver/commit/68fe565adbf32aa4d478d23338d0ee3d9e7ac1a0 and will be included in the next version of **quiver**, which I hope to release soon. Thanks for the bug report @CrossMaze!
