### ISSUE TITLE
Use of small images

### ISSUE THREAD

**Issue by pdehaye** [varkor/quiver#168]
I have found it very useful for diagramming to use emojis as labels on nodes or arrows, sometimes in combinations of multiple symbols. However the range of icons is limited and I would definitely take advantage of the possibility to import small images. Is this possible?

**Comment by kokic** [comment]
**Yes, and very easy.**

As proof and also as an example, I will first show you a picture as an effect. 
![quiver_embed_image](https://github.com/varkor/quiver/assets/22560946/f204f191-4cec-47f5-8106-3e7d3b4c6903)

In the lower right corner of the diagram, I used this image [khan-academy.png](https://katex.org/img/khan-academy.png). 

This is possible because of two facts:
1. quiver is currently relying on KaTeX as a formula renderer. 
2. KaTeX has such a macro `\includegraphics`.

We just need to write directly: 
 ```
\includegraphics[height=0.8em, totalheight=0.9em, width=0.9em, alt=KA logo]{https://katex.org/img/khan-academy.png}
```

But currently it doesn't work in quiver. According to the notes about security issues pointed out [here](https://katex.org/docs/supported.html):

> The following "raw HTML" features are potentially dangerous for untrusted inputs, so they are disabled by default, and attempting to use them produces the command names in red ... To fully trust your LaTeX input, you need to pass an option of trust: true; you can also enable just some of the commands or for just some URLs via the trust option.

This embedding is a security risk, even though it rarely happens.  But if you ignore this, you just need to make some changes in `ui.js`, and everything will work fine.

```js
katex.render(
  cell.label.replace(/\$/g, "\\$"),
  label.element, 
  {
    throwOnError: false,
    errorColor: "hsl(0, 100%, 40%)",
    macros: ui.latex_macros(), 
    trust: true,  // what we do
  },
);
```

**Comment by kokic** [comment]
So as a possible solution, if we can properly handle security issues, we can support `\includegraphics` in the future of quiver.

**Comment by varkor** [comment]
@kokic: thanks for the potential solution! Since **quiver** diagrams store the macro URL they use, I would want to be careful about automatically `trust`ing macros when loading a diagram. However, it could be possible to allow the user to specify, in the UI, that the macro URL is safe to `trust`, which would alleviate this concern.

I'm hoping to spend some more time on **quiver** in the near future, so I'll give some thought to this feature request.

**Comment by varkor** [comment]
I decided it should be reasonable to allow the use of `\url`, `\href`, and `\includegraphics` in **quiver** diagrams (but not the [non-standard HTML commands](https://katex.org/docs/supported.html#html)), and have added support in https://github.com/varkor/quiver/commit/f5c54958ac12e2ee965faf9e0ce1f4e2106d961f. Images will therefore be supported in the next version. Thanks @kokic for the suggestion!
