### ISSUE TITLE
quiver local, allows to break lines of an equation in a quiver box, the exported latex code does not compile

### ISSUE THREAD

**Issue by ouboub** [varkor/quiver#178]
Hi
first many thanks for this wonderful software.

I can add 
\int f dx=0\\ \frac{dg}{dt}=g^2
and it gets displayed nicely in a box, looking like a single multi-line equation, however it is exported as
```
% file:///home/oub/Desktop/quiver/src/index.html#q=WzAsMSxbMCwwLCJcXGludCBmIGR4PTBcXFxcIFxcZnJhY3tkZ317ZHR9PWdeMiJdXQ==
\[\begin{tikzcd}
	{\int f dx=0\\ \frac{dg}{dt}=g^2}
\end{tikzcd}\]
```
for which the compilation fails
```
34 Error   Missing } inserted.
```
regards
Uwe Brauer

**Comment by varkor** [comment]
Thanks for reporting this issue. Unfortunately, I know about it, but it's not something I have control over. Newlines should not be permitted in **quiver**, but KaTeX accepts them (https://github.com/KaTeX/KaTeX/issues/3773). This issue is already tracked by https://github.com/varkor/quiver/issues/136, but I don't expect a fix until the upstream KaTeX issue is resolved.

**Comment by ouboub** [comment]
Ok I see, I found a solution meanwhile, I use and array, which works with quiver and KaTeX, I am not sure whether 
this issue is covered by the documentation...
