### ISSUE TITLE
Issue in makefile - request for a one-click install?

### ISSUE THREAD

**Issue by johnf-robert** [varkor/quiver#210]
makefile displays an error at execution. 
makefile(24) : fatal error U1000: syntax error : ')' missing in macro invocation
Stop.... 
Do you have an easy way to install the app locally without technical steps in Windows. I tried so many things following the processes blindly and nothing worked...I am not familiar with node.js, npm packages, and so on.
Same nightmare for installing Katex...
I expect a one-click install.
Thank you. This application is a great job. I was waiting for that.

**Comment by kokic** [comment]
It is actually quite easy to install quiver locally. Even if using a completely manual approach, this may be more helpful in helping you understand how clean and pure the environment that quiver relies on is :)

Here are the steps:

1. Download the source code, you can use `git clone` or click the link https://github.com/varkor/quiver/archive/refs/heads/master.zip
2. If you selected the link download method in step 1, unzip to the location you need
3. As a step in the complete localization process, you also need to store a katex locally and be able to **be correctly found by quiver**. Similarly, you can still directly download the built katex through the link https://github.com/KaTeX/KaTeX/releases/download/v0.16.9/katex.zip
4. Extract the file to `quiver-master/src`, in other words, quiver needs to find `katex.min.js` and other things (such as style files `.css` and fonts `.ttf`) in the folder `src/katex`
5. open `quiver-master/src/index.html`

---

Supplementary explanation:

- Regarding step 4, the correct path for katex, even if quiver makes changes to it in the future, you can still find this correct path through the following methods: Enter file `quiver-master/src/ui.js` and search for `katex.min.js`, You will see that currently it is `KaTeX/katex.min.js`, Due to the insensitivity of Windows file system to case, even if  lowercase `katex` was present before, it still worked very well. 
- If you encounter permission issues on other devices, specifically, you cannot use quiver by directly opening `index. html`. In this case, you only need to run a local static web server in the current path. Many language runtime environments come with this feature, such as `python -m http.server`

**Comment by varkor** [comment]
Hi @johnf-robert, you probably don't need to build **quiver** manually using the Makefile. If you simply want to use **quiver** offline, as long as you have visited https://q.uiver.app/ at least once, you will be able to open it without an internet connection in the future. If you want to use it as a standalone app, you can also install it from the webpage. For instance, on Chrome, you can click on this icon in the URL bar:
<img width="347" alt="image" src="https://github.com/varkor/quiver/assets/3943692/788990ec-7d39-4850-999b-c3664551e215">
(Unfortunately, this feature does not seem to be supported in Firefox at the moment, but you can still use **quiver** offline through the browser in this case.)

Currently, the only reason to use the Makefile is if you want to modify your own copy of **quiver**, the main task of the Makefile is to download KaTeX, which can easily be done manually as @kokic has explained (thank you @kokic!).
