### ISSUE TITLE
Clicking outside the about dialog should close it

### ISSUE THREAD

**Issue by user202729** [varkor/quiver#229]
Currently it's not, and the behavior seems confusing.

(On an unrelated note it is also slightly confusing that other dialogs e.g. "generate LaTeX code" also needs to click again on **that button** or press Escape to close it. But I can't really think of a good way against this, because the dialog is the whole screen so there's no "outside". Perhaps make a [←] button somewhere? Compared to [TIO](https://tio.run/#mathematica)'s approach of hiding the whole button list and show a [←] button)

**Comment by varkor** [comment]
I don't have a strong preference either way, so I've implemented your suggestion in https://github.com/varkor/quiver/commit/97d2eef1b0fa84620b8ea86c2b1d48b695c6505b.

> Perhaps make a [←] button somewhere?

I suppose this would be possible. My feeling was that there weren't many obvious options to close such modal dialogues, so that, even if it wasn't immediately clear to the user how to close them, they would quickly figure it out. But perhaps it is worth making a more obvious button. I think it would be better to open a new issue for this if you do think the current behaviour is unclear, though.
