### ISSUE TITLE
Using within align environment

### ISSUE THREAD

**Issue by AviSteiner** [varkor/quiver#51]
The code

```
\documentclass{article}
\usepackage{amsmath}
\usepackage{quiver}

\begin{document}

% https://q.uiver.app/?q=WzAsMixbMCwwLCJQIl0sWzEsMCwiUSJdLFswLDEsIlxcdmFycGhpIiwwLHsib2Zmc2V0IjotMX1dLFswLDEsIjAiLDIseyJvZmZzZXQiOjF9XV0=
\begin{align}
    \begin{tikzcd}
    	{P} & {Q}
    	\arrow["{\varphi}", from=1-1, to=1-2, shift left=1]
    	\arrow["{0}"', from=1-1, to=1-2, shift right=1]
    \end{tikzcd}
\end{align}

\end{document}
```
produces the error
![image](https://user-images.githubusercontent.com/43213102/100483607-8ef55500-30c7-11eb-9192-e210cbe85ab2.png)

When `align` is replaced by `equation`, this doesn't happen. Is this a problem with tikzcd or with quiver?

**Comment by varkor** [comment]
`&` [has a different meaning](https://tex.stackexchange.com/a/324788) inside `align`, which is conflicting with the meaning inside `tikzcd`. You can use the `ampersand replacement` option to overwrite the tikz-cd symbol:
```latex
\begin{align}
    \begin{tikzcd}[ampersand replacement=\&]
    	{P} \& {Q}
    	\arrow["{\varphi}", from=1-1, to=1-2, shift left=1]
    	\arrow["{0}"', from=1-1, to=1-2, shift right=1]
    \end{tikzcd}
\end{align}
```
I'm not sure whether this is something I want to handle inside quiver directly, because I think this is a fairly uncommon use-case (as opposed to using `equation`, for instance), and when it is needed, one can perform the ampersand replacement manually.

If you disagree, let me know, and we can discuss a possible solution.

**Comment by varkor** [comment]
I've opened an issue for ampersand replacement here: https://github.com/varkor/quiver/issues/51, because I think it would be a useful option.
