### ISSUE TITLE
how to use it in beamer?

### ISSUE THREAD

**Issue by rhocos3theta** [varkor/quiver#52]
\begin{frame}

\[\begin{tikzcd}
	{M(f,d,y)} && {G} \\
	\\
	{E} &&&&& {A}
	\arrow["{(m_0,m_1)\longleftarrow F^G(E)}"', from=3-6, to=3-1, shift right=1, curve={height=18pt}]
	\arrow["{\alpha \longleftarrow y||s}"', from=3-1, to=3-6, shift right=1, curve={height=18pt}]
	\arrow["{r \ or \ random \ string }"', from=3-6, to=1-3]
\end{tikzcd}\]

\end{frame}

when i compile it tells me wrong,but i can compile without \begin{frame}

**Comment by varkor** [comment]
I wasn't able to get your code to compile even without `frame`, but I think this may be caused by `frame` overriding the cell spacing character `&` (see [this question](https://tex.stackexchange.com/questions/211774/beamer-tikz-cd-problem) or [this question](https://tex.stackexchange.com/questions/119870/problems-with-beamer-and-diagrams-in-tikz) on TeX.SE). There are two ways to get around this: by using `\begin{frame}[fragile]`, or by using `\begin{tikzcd}[ampersand replacement=\&]` and replacing the ampersands in the diagram with `\&` instead. It's a little hard to get around this in quiver itself, as this fix is dependent on the context in which the diagram appears. Could you try those and see if it works?

**Comment by rhocos3theta** [comment]
I success after using ` \begin{frame}[fragile]` .Thank you very much for your help !!!💯

**Comment by varkor** [comment]
Glad to hear that worked!
