### ISSUE TITLE
Natural transformation arrows are tilted

### ISSUE THREAD

**Issue by oxidist** [varkor/quiver#71]
When drawing arrows between arrows, it seems that quiver chooses different centers for the curved ones, thus [resulting](https://q.uiver.app/?q=WzAsMyxbMCwwLCJcXG1hdGhzY3IgQSJdLFsyLDAsIlxcbWF0aHNjciBBJyJdLFs0LDAsIlxcbWF0aHNjciBBJyciXSxbMCwxLCJIIiwyLHsiY3VydmUiOjR9XSxbMCwxLCJGIiwwLHsiY3VydmUiOi00fV0sWzAsMV0sWzEsMiwiSCciLDIseyJjdXJ2ZSI6NH1dLFsxLDIsIkYnIiwwLHsiY3VydmUiOi00fV0sWzEsMl0sWzUsMywiXFxiZXRhIiwwLHsic2hvcnRlbiI6eyJzb3VyY2UiOjIwLCJ0YXJnZXQiOjIwfX1dLFs0LDUsIlxcYWxwaGEiLDAseyJzaG9ydGVuIjp7InNvdXJjZSI6MjAsInRhcmdldCI6MjB9fV0sWzgsNiwiXFxiZXRhJyIsMCx7InNob3J0ZW4iOnsic291cmNlIjoyMCwidGFyZ2V0IjoyMH19XSxbNyw4LCJcXGFscGhhJyIsMCx7InNob3J0ZW4iOnsic291cmNlIjoyMCwidGFyZ2V0IjoyMH19XV0=) in tilted arrows. The problem is worse when the code is copied into a latex file (I'm using the Linux Libertine font in the following screenshot):
![image](https://user-images.githubusercontent.com/8658852/104744595-0e6fde00-5773-11eb-81c0-4a6fd9d7b59b.png)

**Comment by varkor** [comment]
**quiver** always picks the midpoint of the arc, as drawn. I believe TikZ does the same, but due to slight rendering differences, it can appear slightly different. The effect is more easily seen when one of the objects is much wider:
[![Skew 2-cells](https://user-images.githubusercontent.com/3943692/104788250-bc868280-5789-11eb-84dd-80ae16a3b5f7.png)](https://q.uiver.app/?q=WzAsMixbMCwwLCJBIl0sWzIsMCwiQUFBQUFBQUFBQUFBQUEiXSxbMCwxLCIiLDIseyJjdXJ2ZSI6NH1dLFswLDEsIiIsMCx7ImN1cnZlIjotNH1dLFswLDFdLFs0LDIsIiIsMCx7InNob3J0ZW4iOnsic291cmNlIjoyMCwidGFyZ2V0IjoyMH19XSxbMyw0LCIiLDAseyJzaG9ydGVuIjp7InNvdXJjZSI6MjAsInRhcmdldCI6MjB9fV1d)
The issue is that the arrows are always drawn to the centre of the object, and curved arrows may be much longer than straight lines in general, so the midpoints may not line up.

I'm not sure what the best way to address this is: I don't think the current behaviour is wrong (setting the centre to always be the average of the two object positions will result in 2-cells being drawn pointing to the object label if one object is wide enough, so this would not be correct). I'd be happy to hear suggestions. Perhaps being able to manually alter the "centre" of each arrow would be the simplest way to address this, but it could be quite difficult to get it perfect.

**Comment by vikraman** [comment]
I've encountered this before, this isn't really a quiver/tikz issue since the object labels have different widths, so my workaround was to just use a parbox with fixed width for the labels.

**Comment by oxidist** [comment]
> I've encountered this before, this isn't really a quiver/tikz issue since the object labels have different widths, so my workaround was to just use a parbox with fixed width for the labels.

That works pretty well, thanks. I'll be closing this issue then, seeing that it isn't related to quiver.
