### ISSUE TITLE
String Diagrams?

### ISSUE THREAD

**Issue by tcampion** [varkor/quiver#78]
I wanted to leave this as a comment on your blog, but it looks like maybe it doesn't have a comment section at all. I apologize if this is the wrong place to bring it up. I haven't really used quiver much yet, but it looks really really cool and I'm looking forward to trying it out!

Probably a string diagram editor would be a whole 'nother undertaking, and likely most appropriately addressed with a completely different app. But I'm curious if you've thought at all about making such a thing, or know if anybody else has?

Drawing string diagrams in tikz is even more of a chore than commutative diagrams. It's also more niche (though since you support 2-dimensional arrows, maybe it's the sort of niche market you might be interested in servicing?) It would be really cool to have a tool allowing one to make such diagrams without manually working out spacing of nodes and so forth.

Anyway, just a wishful suggestion. Thanks for making this!

**Comment by varkor** [comment]
I'm happy to use GitHub for these kind of conversations (there's also the GitHub [Discussions page](https://github.com/varkor/quiver/discussions), which caters a little better to more general discussion).

Using **quiver** as a base for a string diagram editor has crossed my mind. There are some components that would need to be entirely new: namely the rendering and manipulation of string diagrams. I've not thought about this in detail, so I don't have an idea for how significant an undertaking this in particular would be. On the other hand, a lot of the general UI  could be reused or repurposed, which would save time.

I suspect that if string diagrams were easier to draw and manipulate on a computer, they would be more popular, and I think it would be great to have a general purpose string diagram editor. That said, **quiver** came about because I was frustrated by the process of creating commutative diagrams; I haven't personally started using string diagrams in my own work yet, so I have less immediate incentive to make the process better.

If there are others who are interested in bringing about such a tool, I would be interested to discuss the possibilities. While I don't have time at the moment to develop a string diagram editor myself, I would happily make **quiver**'s implementation more flexible and extensible to facilitate the development of another tool.

**Comment by tcampion** [comment]
Thanks for the reply! I'm not a developer myself, nor am I familiar with the kind of work required to bring together developers and users on projects like this, so it's unlikely that I personally would be seriously trying to drum up such a project in the near future. But I'll keep in mind your openness to helping facilitate the infrastructure in case the opportunity presents itself. And who knows -- maybe somebody else will stumble upon this conversation and take you up on it!

Thanks!

**Comment by varkor** [comment]
I'm going to close this issue for now, as not in scope, but at some point in the future it may become more of a possibility.
