### ISSUE TITLE
Add option for ampersand replacement

### ISSUE THREAD

**Issue by varkor** [varkor/quiver#87]
It's quite common to get into situations where `&` has some special behaviour and interacts badly with TikZ, necessitating the use of `ampersand replacement`. It would be nice to allow **quiver** to export this option automatically. See https://github.com/varkor/quiver/issues/51.

**Comment by i5qme2b944w3** [comment]
If building an `ampersand replacement` option into quiver is too much, an easier alternative could be to just place a warning somewhere in the quiver UI that these `&` conflicts happen and can be resolved by (manual) use of `ampersand replacement`.

This could at least save some users a bit of googling. (Although this issue is documented in the tikzcd manual, it is hardly obvious to the user who tries putting their diagram in an `align` environment, only to have their document fail to compile...).

**Comment by varkor** [comment]
It will not be a difficult feature to implement. Unfortunately, I don't have time to work on **quiver** right now, as I am in the process of completing my PhD thesis. I will return to **quiver** once that is complete. I agree it is an awkward error to get at the moment.

**Comment by varkor** [comment]
This has been added in https://github.com/varkor/quiver/commit/b1e2e1b9ea491f057d766cc01cd369f71d551e43, which will be available in the next version of **quiver**.
