### ISSUE TITLE
Support tikzcd's column/row sep

### ISSUE THREAD

**Issue by iLambda** [varkor/quiver#98]
When writing diagrams with verbose labels, they tend to get overflow and nearly hide the arrows.
![image](https://user-images.githubusercontent.com/2763457/121194983-81d3d280-c86f-11eb-8734-ce17cecb2d9d.png)

To fix this, in latex, I add `[column sep=small/normal/huge/large, row sep=small/normal/huge/large]`, which produces a more readable output. 
![image](https://user-images.githubusercontent.com/2763457/121195043-8e582b00-c86f-11eb-9478-e6061396c660.png)

In order to ensure reproducibility (coauthor editing the diagram on q.uiver and then forgetting to put the annotations back), it would be nice to have a way to specify it in q.uiver so that the preview can be easier to make, and read.

**Comment by varkor** [comment]
I've been meaning to get around to adding this, because I hit the same problems. I'll try to get to it soon.

**Comment by enjoysmath** [comment]
@varkor  note, if you have an editable list of labels for the nodes, then one way of coding it is so that  no label is the "center label", so you could have the node highlight when you hover over it for moving, and the labels can move around and bound to a smaller grid which may or may not be visible.   So that the dimensions of your large grid never really change,  and you don't have any longer the bugs it is causing such as this one.  By editable list of labels I mean multiple labels per arrow but in addition per node.  See comment in other thread about that feature: #92

Perhaps if their is only one label, then the node moves along with its label by default.

**Comment by varkor** [comment]
Yes, I think there's some room for experimentation here. I was wondering whether having the label length affect the grid size would work well. It does seem a more natural solution than fixed column size like tikz-cd. I'd have to play around with it to see, though.

**Comment by varkor** [comment]
Since I haven't had time to experiment with more flexible column/row spacing behaviour, I've implemented some sliders on the export screen that allow you to change the separation manually. This won't be reflected in the **quiver** diagram, but will add the `column sep` and `row sep` tikz-cd options. At the moment, column and row spacing is not saved in the diagram itself, but hopefully this is still useful for the time being.
<img width="903" alt="image" src="https://user-images.githubusercontent.com/3943692/178364695-41551446-8222-4b06-979b-87649d1fc6a9.png">
Let me know if this doesn't address your use case.

This has been added in https://github.com/varkor/quiver/commit/d2c8c1dcc44fcfc398bfe03138cf90e870fbab20 and will be available in the next version of **quiver**, which I hope to release soon. You can test it on https://q.uiver.app/dev/.
